/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AwsAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AwsSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubOwner": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubRepo": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KakaoAppKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KakaoSearchClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NaverMapClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PinPlateWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "S3BucketName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "XaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}